default_platform(:mac)

DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]

def get_api_key()
  return app_store_connect_api_key(
    key_id: APPLE_KEY_ID,
    issuer_id: APPLE_ISSUER_ID,
    key_content: APPLE_KEY_CONTENT,
    duration: 1200,
    in_house: false
  )
end

platform :mac do
  lane :get_cert do
    create_keychain(
      name: TEMP_KEYCHAIN_USER,
      password: TEMP_KEYCHAIN_PASSWORD,
      unlock: false,
      default_keychain: true,
      timeout: 0
    )

    match(
      type: "developer_id",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      skip_provisioning_profiles: true,
      keychain_name: TEMP_KEYCHAIN_USER,
      keychain_password: TEMP_KEYCHAIN_PASSWORD,
      api_key: get_api_key()
    )
  end

  lane :make_safe do
    notarize(
      package: "Techmino-macOS.dmg",
      bundle_id: "org.love2d.dummy",
      use_notarytool: true,
      print_log: true,
      api_key: get_api_key()
    )
  end
end
